# Generated by Django 3.0.7 on 2020-06-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=19)),
                ('brand', models.CharField(blank=True, max_length=2, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('unit', models.CharField(choices=[('gr', 'Gram'), ('kg', 'kilogram'), ('adet', 'Adet'), ('packet', 'Packet')], max_length=10, null=True)),
                ('currency', models.CharField(choices=[('TL', 'TURK LIRASI')], max_length=3, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('meta_data', models.TextField(blank=True, null=True)),
                ('is_returnable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('active', models.BooleanField(default=True, help_text='Is this product publicly visible.', verbose_name='Active')),
            ],
        ),
    ]
