# Generated by Django 3.0.7 on 2020-06-18 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20200618_2210'),
        ('products', '0002_auto_20200614_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='properties',
            field=models.ManyToManyField(blank=True, null=True, to='products.BaseProperty'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Brand'),
        ),
    ]
